name: Connect to GCP and List Instances

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Get OIDC Token'
      id: get_oidc_token
      uses: actions/github-script@v4
      with:
        script: |
          const token = await core.getIDToken("https://composite-set-363417.svc.id.goog")
          core.setOutput('oidc_token', token)
